openapi: 3.0.0
info:
  title: Workforce
  description: |-
      Turn centralizes data on each worker to define a unique job profile consisting of identity and performance data.
      Partners provide this information to Turn through the Workforce API.

      ## About *turn_id*
      The turn_id is the unique id provided by Turn through the screening of a candidate. This unique id is an 11 character string starting with a ‘C’ and followed by 10 digits (ex. C1279030625).
      The Turn ID is required to be specified in the URL indicated as <turn_id> in the documentation. 
      If the Turn ID is not included, the information will not be correctly shared.

      ## About record *id*
      Some records posted have a unique id. These unique ids are the identifiers generated by your system and do not need to follow a specified format. They can be sequential numbers or an alphanumeric UUID system.
  contact: {}
  version: '1.0'
servers:
  - url: 'https://api.turning.io/v1'
    variables: {}
paths:
  '/workforce/{turn_id}/profile':
    post:
      tags:
        - Workforce
      summary: Profile
      description: "The Profile endpoint is responsible for collecting basic worker information. You should provide this information once a worker is accepted and able to start working on your platform.\nIf the worker updates their information (a new email address, phone number or name), you should provide the updated information through the API to update our records.\nThe following attributes are passed as parameters to this endpoint: \n\n\n\n|Parameter\t\t\t|Required\t|Type\t\t|Description\n|:-----------\t\t|:---------:|------:\t|:-----------\n|first_name\t\t\t|true\t\t|`string`\t\t|Legal first name of the worker\n|last_name\t\t\t|true\t\t|`string`\t\t|Legal last name of the worker\n|email\t\t\t|false\t\t|`string`\t\t|Valid email of the worker\n|phone_number\t\t\t|false\t\t|`string`\t\t|Mobile phone number of the worker, 11 digits. (ex. 18645404931)"
      operationId: Profile
      parameters:
        - name: turn_id
          in: path
          description: Turn Id as provided once turn processed a background check
          required: true
          style: simple
          schema:
            type: string
            example: C1279030625
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileRequest'
            example:
              first_name: Tracy
              last_name: Noseworthy
              email: example@turning.io
              phone_number: '18645404931'
        required: true
      responses:
        '200':
          description: OK
          headers:
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Server:
              content:
                text/plain:
                  schema:
                    type: string
                  example: gunicorn/19.6.0
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'Thu, 18 Jun 2020 23:33:08 GMT'
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '24'
            Access-Control-Allow-Origin:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            Strict-Transport-Security:
              content:
                text/plain:
                  schema:
                    type: string
                  example: max-age=31536000
            Via:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 1.1 vegur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200Success5'
              example:
                message: OK
      deprecated: false
  '/workforce/{turn_id}/task':
    post:
      tags:
        - Workforce
      summary: Task
      description: "The Task endpoint holds the information about all tasks completed by the worker.\n\n## About *task_type*\nValid types (delivery, pet-care, mealshare, ride-share, child-care, home-services, education, creative-service, security, storage, cooking, brand-ambassador, fashion-beauty, device-repair, personal-trainer, software-testing, personal-assistant, secret-shopper, tour-guide, real-state, medical-delivery, moving, cleaning, caregiving).\n\n\n\nThe following attributes are to be passed as parameters to this endpoint:\n\n\n\n|Parameter\t\t\t|Required\t|Type\t\t|Description\n|:-----------\t\t|:---------:|------:\t|:-----------\n|id\t\t\t|true\t\t|`string`\t\t|Unique id for the task record\n|type\t\t\t|true\t\t|`string`\t\t|Type of task (e.g. “delivery”, “pet-care”, “child-care”, etc)\n||||See about task_type for full list of available types\n|status         |true\t|`string`\t\t|Status of the task (“completed”, “canceled”)\n|canceled_by   |Optional ( if status is canceled)\t\t|`string`\t\t|Cancelation requested by (“worker”, “customer”)\n|start_location.lat\t\t\t|false  \t|`float`\t\t|Latitude of geo point where the task started (pickup-location for delivery and ridesharing, address-location for services and care)\n|start_location.lng\t\t\t|false\t\t|`float`\t\t|Longitude of geo point where the task started\n|start_location.formatted_address\t\t\t|false\t\t|`string`\t\t|Address line where the task started (with city, state & zip)\n|end_location.lat\t\t\t|false\t\t|`float`\t\t|Latitude of geo point where the task finished\n|end_location.lng\t\t\t|false\t\t|`float`\t\t|Longitude of geo point where the task finished\n|end_location.formatted_address\t\t\t|false\t\t|`float`\t\t|Address line where the task finished (with city, state & zip)\n|distance\t\t\t|false\t\t|`float`\t\t|Distance travelled for task (lat / lng of start vs. lat / lng of end) in miles\n|start_date\t\t\t|false\t\t|`datetime`\t\t|Timestamp when the task started\n|end_date\t\t\t|false\t\t|`datetime`\t\t|Timestamp when the task finished\n|duration\t\t\t|false\t\t|`integer`\t\t|Duration of the task in minutes\n|num_task\t\t\t|false\t\t|`integer`\t\t|Number of tasks completed in this assignment (defaults to 1)"
      operationId: Task
      parameters:
        - name: turn_id
          in: path
          description: Turn Id as provided once turn processed a background check
          required: true
          style: simple
          schema:
            type: string
            example: C1279030625
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskRequest'
            example:
              id: 1234-5678-9123
              status: completed
              type: delivery
              start_location:
                lat: '43.005895'
                lon: '-71.013202'
                formatted_address: '299 Main Street, Greenville, SC, USA'
              end_location:
                lat: '43.70895'
                lon: '-71.913202'
                formatted_address: '104 Greer Street, Greenville, SC, USA'
              distance: 3.5
              start_date: '2020-05-24 15:09:00'
              end_date: '2020-05-24 15:29:00'
              duration: 0.33
              num_tasks: 1
        required: true
      responses:
        '200':
          description: OK
          headers:
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Server:
              content:
                text/plain:
                  schema:
                    type: string
                  example: gunicorn/19.6.0
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'Mon, 22 Jun 2020 19:24:03 GMT'
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '24'
            Access-Control-Allow-Origin:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            Strict-Transport-Security:
              content:
                text/plain:
                  schema:
                    type: string
                  example: max-age=31536000
            Via:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 1.1 vegur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200Success5'
              example:
                message: OK
      deprecated: false
  '/workforce/{turn_id}/address':
    post:
      tags:
        - Workforce
      summary: Address
      description: "The Address endpoint provides the address of the worker.\nIf the worker updates their information, you should provide the updated address through the API to make sure our records are always up to date.\nThe following attributes are passed as parameters to this endpoint: \n\n\n\n|Parameter\t\t\t|Required\t|Type\t\t|Description\n|:-----------\t\t|:---------:|------:\t|:-----------\n|postal_code\t|true\t\t|`string`\t\t|Zip code of the worker’s current address\n|city\t\t\t|false\t\t|`string`\t\t|City of the worker’s current address\n|state\t\t|false\t\t|`string`\t\t|State of the worker’s current address, 2 characters  (“CA”, “NY”)\n|country\t\t\t|false\t\t|`string`\t\t|Country of the worker’s current address in 2 character ISO (“US”, “CA”)\n|address_ln\t\t\t|false\t\t|`string`\t\t|Street address as a single string (“123 Main Street Apt A”)"
      operationId: Address
      parameters:
        - name: turn_id
          in: path
          description: Turn Id as provided once turn processed a background check
          required: true
          style: simple
          schema:
            type: string
            example: C1279030625
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddressRequest'
            example:
              city: Spartanburg
              country: US
              state: SC
              address_ln: 299 Main Street
              postal_code: '29306'
        required: true
      responses:
        '200':
          description: OK
          headers:
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Server:
              content:
                text/plain:
                  schema:
                    type: string
                  example: gunicorn/19.6.0
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'Mon, 22 Jun 2020 19:33:33 GMT'
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '24'
            Access-Control-Allow-Origin:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            Strict-Transport-Security:
              content:
                text/plain:
                  schema:
                    type: string
                  example: max-age=31536000
            Via:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 1.1 vegur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200Success5'
              example:
                message: OK
      deprecated: false
  '/workforce/{turn_id}/vehicle':
    post:
      tags:
        - Workforce
      summary: Vehicle
      description: "The Vehicle endpoint collects information about transportation modes for the worker.\nIf the worker updates their modes of transportation, you should provide the update through the API to update our records.\n\n## About *type*\nValid types: car, walk, motorbike, bicycle, pickup-truck, van, truck, public-transport. If you have a vehicle type not listed, contact support@turning.io\n\n\nThe following attributes are to be passed as parameters to this endpoint: \n\n\n|Parameter\t\t\t|Required\t|Type\t\t|Description\n|:-----------\t\t|:---------:|------:\t|:-----------\n|id\t\t\t|true\t\t|`string`\t\t|Unique id for the vehicle record\n|type\t    |true\t\t|`string`\t\t|Type of vehicle. See “About type” to see available values.\n|make\t\t|false\t\t|`string`\t\t|Make or brand of the vehicle\n|model\t\t|false\t\t|`string`\t\t|Model of the vehicle\n|year\t\t|false\t\t|`integer`\t\t|Year of the vehicle was made\n|identification_number\t\t|false\t\t|`string`\t\t|Vehicle identification (license plate) number\n|identification_state\t\t|false\t\t|`string`\t\t|Vehicle identification (license plate) state, 2 characters (“CA”, “NY”)\n|doors\t\t\t|false\t\t|`integer`\t\t|Number of doors the vehicle has (2, 4)"
      operationId: Vehicle
      parameters:
        - name: turn_id
          in: path
          description: Turn Id as provided once turn processed a background check
          required: true
          style: simple
          schema:
            type: string
            example: C1279030625
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleRequest'
            example:
              make: honda
              model: accord
              year: '1999'
              identification_number: '239873243'
              identification_state: MO
              type: car
        required: true
      responses:
        '200':
          description: OK
          headers:
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Server:
              content:
                text/plain:
                  schema:
                    type: string
                  example: gunicorn/19.6.0
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'Mon, 22 Jun 2020 20:26:33 GMT'
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '24'
            Access-Control-Allow-Origin:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            Strict-Transport-Security:
              content:
                text/plain:
                  schema:
                    type: string
                  example: max-age=31536000
            Via:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 1.1 vegur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200Success5'
              example:
                message: OK
      deprecated: false
  '/workforce/{turn_id}/payout':
    post:
      tags:
        - Workforce
      summary: Payout
      description: "The Payout endpoint tracks the income a worker has earned.\nThe following attributes are to be passed as parameters to this endpoint: \n\n\n|Parameter\t\t\t|Required\t|Type\t\t|Description\n|:-----------\t\t|:---------:|------:\t|:-----------\n|id\t\t\t|true\t\t|`string`\t\t|Unique id for the payout record\n|status\t    |true\t\t|`string`\t\t|Status of the payment (“completed”, “canceled”)\n|type\t\t|true\t\t|`string`\t\t|Type of payment (“check”, “cash”, “direct_deposit”)\n|payout_date\t\t|true\t\t|`date`\t\t|Payment date\n|currency\t\t|true\t\t|`string`\t\t|Currency of the payment in 3-letter ISO (“USD”, “CAD”)\n|gross_pay\t\t|false\t\t|`float`\t\t|Income before taxes and fees\n|deductions\t\t|false\t\t|`float`\t\t|Taxes and fees amount\n|net_pay\t\t|false\t\t|`float`\t\t|Payment amount after deductions\n|hours\t\t|false\t\t|`float`\t\t|Hours worked involved in the paycheck\n|tasks\t\t|false\t\t|`integer`\t\t|Total of tasks performed in the payment cycle"
      operationId: Payout
      parameters:
        - name: turn_id
          in: path
          description: Turn Id as provided once turn processed a background check
          required: true
          style: simple
          schema:
            type: string
            example: C1279030625
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PayoutRequest'
            example:
              id: D123-2134-43234
              status: completed
              type: direct_deposit
              payout_date: '2020-06-11'
              currency: USD
              gross_pay: 20
              deductions: 5
              net_pay: 25
              hours: 1
        required: true
      responses:
        '200':
          description: OK
          headers:
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Server:
              content:
                text/plain:
                  schema:
                    type: string
                  example: gunicorn/19.6.0
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'Mon, 22 Jun 2020 20:37:37 GMT'
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '24'
            Access-Control-Allow-Origin:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            Strict-Transport-Security:
              content:
                text/plain:
                  schema:
                    type: string
                  example: max-age=31536000
            Via:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 1.1 vegur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200Success5'
              example:
                message: OK
      deprecated: false
  '/workforce/{turn_id}/career':
    post:
      tags:
        - Workforce
      summary: Career
      description: "The Career endpoint stores information about a worker’s career history.\nThe following attributes are to be passed as parameters to this endpoint:  \n\n\n|Parameter\t\t\t|Required\t|Type\t\t|Description\n|:-----------\t\t|:---------:|------:\t|:-----------\n|signup_date\t\t\t|Optional (only the first time)\t\t|`datetime`\t\t|Date when the worker initially signed up for a worker account\n|length_at_work\t    |false\t\t|`integer`\t\t|Days since first activity date(II)\n|total_hours_spent_working\t\t|false\t\t|`integer`\t\t|Total hours completing tasks.\n|first_activity_date\t\t|false\t\t|`datetime`\t\t|Date when the first task was completed(II)\n|last_activity_date\t\t|false\t\t|`datetime`\t|Date when the last task was completed(II)\n\n\nII. If you are passing Task information using the Tasks endpoint, this value will be calculated based on the worker’s task history."
      operationId: Career
      parameters:
        - name: turn_id
          in: path
          description: Turn Id as provided once turn processed a background check
          required: true
          style: simple
          schema:
            type: string
            example: C1279030625
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CareerRequest'
            example:
              signup_date: '2020-01-04 19:00:00'
              length_at_work: 200
              total_hours_spent_working: 320
              first_activity_date: '2020-01-04 19:00:00'
              last_activity_date: '2020-06-20 11:21:17'
        required: true
      responses:
        '200':
          description: OK
          headers:
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Server:
              content:
                text/plain:
                  schema:
                    type: string
                  example: gunicorn/19.6.0
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'Mon, 22 Jun 2020 22:03:09 GMT'
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '24'
            Access-Control-Allow-Origin:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            Strict-Transport-Security:
              content:
                text/plain:
                  schema:
                    type: string
                  example: max-age=31536000
            Via:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 1.1 vegur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200Success5'
              example:
                message: OK
      deprecated: false
  '/workforce/{turn_id}/reputation':
    post:
      tags:
        - Workforce
      summary: Reputation
      description: "The Reputation endpoint tracks a worker’s performance and reputation.\nThe following attributes are to be passed as parameters to this endpoint:  \n\n\n|Parameter\t\t\t|Required\t|Type\t\t|Description\n|:-----------\t\t|:---------:|------:\t|:-----------\n|rating\t\t\t|true\t\t|`float`\t\t|Customer ratings in range of 5 to 0\n|acceptance_rate    |true\t\t|`float`\t|Acceptance rate of offered tasks in range of 1 to 0"
      operationId: Reputation
      parameters:
        - name: turn_id
          in: path
          description: Turn Id as provided once turn processed a background check
          required: true
          style: simple
          schema:
            type: string
            example: C1279030625
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReputationRequest'
            example:
              rating: 4.5
              acceptance_rate: 0.45
        required: true
      responses:
        '200':
          description: OK
          headers:
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Server:
              content:
                text/plain:
                  schema:
                    type: string
                  example: gunicorn/19.6.0
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'Tue, 23 Jun 2020 05:49:29 GMT'
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '24'
            Access-Control-Allow-Origin:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            Strict-Transport-Security:
              content:
                text/plain:
                  schema:
                    type: string
                  example: max-age=31536000
            Via:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 1.1 vegur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200Success5'
              example:
                message: OK
      deprecated: false
  '/workforce/external_profile':
    post:
      tags:
        - Workforce
      summary: External Profile
      description: "The external profile endpoint is responsible for collecting worker information regardless previous background checks.\n\nThe following attributes are passed as parameters to this endpoint:\n\n\n|Parameter\t\t\t|Required\t|Type\t\t|Description\n|:-----------\t\t|:---------:|------:\t|:-----------\n|first_name\t\t\t|true\t\t|`string`\t\t|Legal first name of the worker\n|last_name\t\t\t|true\t\t|`string`\t\t|Legal last name of the worker\n|email\t\t\t|false\t\t|`string`\t\t|Valid email of the worker\n|phone_number\t\t\t|false\t\t|`string`\t\t|Mobile phone number of the worker, 11 digits. (ex. 18645404931)\n|date_of_birth\t\t\t|false\t\t|`date`\t\t|Valid date of birth of the worker\n|address\t\t\t|false\t\t|`Address`\t\t|Valid address object*\n|vehicle\t\t\t|false\t\t|`Vehicle`\t\t|Valid vehicle object*\n|task\t\t\t|false\t\t|`Task`\t\t|Valid task object*\n|payout\t\t\t|false\t\t|`Payout`\t\t|Valid payout object*\n|reputation\t\t\t|false\t\t|`Reputation`\t\t|Valid reputation object*\n|career\t\t\t|false\t\t|`Career`\t\t|Valid career object*\n\n## About *address*\nPlease refer to the Address endpoint.\n## About *vehicle*\nPlease refer to the Vehicle endpoint.\n## About *task*\nPlease refer to the Task endpoint.\n## About *payout*\nPlease refer to the Payout endpoint.\n## About *reputation*\nPlease refer to the Reputation endpoint.\n## About *career*\nPlease refer to the Career endpoint."
      operationId: ExternalProfile
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalProfileRequest'
            example:
              first_name: Alex
              last_name: Mendez
              email: your_email@turning.io
              phone_number: '18645404931'
              date_of_birth: '1987-05-24'
              address:
                city: Greer
                country: US
                state: SC
                address_ln: 299 Main Street
                postal_code: '29651'
                is_primary: 'True'
              task:
                id: 1234-5678-9123
                status: completed
                type: delivery
                start_location:
                  lat: '43.005895'
                  lon: '-71.013202'
                  formatted_address: '299 Main Street, Greenville, SC, USA'
                end_location:
                  lat: '43.70895'
                  lon: '-71.913202'
                  formatted_address: '104 Greer Street, Greenville, SC, USA'
                distance: 3.5
                start_date: '2020-05-24 15:09:00'
                end_date: '2020-05-24 15:29:00'
                duration: 1
                num_tasks: 1
        required: true
      responses:
        '200':
          description: OK
          headers:
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Server:
              content:
                text/plain:
                  schema:
                    type: string
                  example: gunicorn/19.6.0
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'Tue, 04 Aug 2020 19:31:47 GMT'
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '24'
            Access-Control-Allow-Origin:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            Strict-Transport-Security:
              content:
                text/plain:
                  schema:
                    type: string
                  example: max-age=31536000
            Via:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 1.1 vegur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200SuccessBasicInfo'
              example:
                message: OK
      deprecated: false
components:
  schemas:
    /fcra_check/form_request:
      title: /fcra_check/form_request
      required:
        - package_id
        - zipcode
      type: object
      properties:
        package_id:
          type: string
        zipcode:
          type: string
      example:
        package_id: P1051539566
        zipcode: '95476'
      x-internal: true
    /fcra_check/form/<check_id>_request:
      title: /fcra_check/form/<check_id>_request
      required:
        - first_name
        - last_name
        - no_middle_name
        - middle_name
        - date_of_birth
        - zipcode
        - phone
        - ssn
        - email
        - drivers_license_number
        - drivers_license_state
        - consent_document
        - callback_url
        - do_checks
        - timestamps
        - metadata
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        no_middle_name:
          type: boolean
        middle_name:
          type: string
        date_of_birth:
          type: string
        zipcode:
          type: string
        phone:
          type: string
        ssn:
          type: string
        email:
          type: string
        drivers_license_number:
          type: string
        drivers_license_state:
          type: string
        consent_document:
          type: string
        callback_url:
          type: string
        do_checks:
          type: boolean
        timestamps:
          $ref: '#/components/schemas/Timestamps'
        metadata:
          $ref: '#/components/schemas/Metadata'
      example:
        first_name: Alec
        last_name: Sadler
        no_middle_name: false
        middle_name: M
        date_of_birth: '1980-11-30'
        zipcode: '95476'
        phone: '18884998876'
        ssn: '123456789'
        email: contact@turning.io
        drivers_license_number: U1234567
        drivers_license_state: CA
        consent_document: 'data:image/png;base64,'
        callback_url: 'https://somedomain.com/response'
        do_checks: true
        timestamps:
          welcome:
            - '2021-06-13T21:40:04.766Z'
          summary_of_rights:
            - '2021-06-13T21:40:05.766Z'
          disclosure:
            - '2021-06-13T21:40:06.766Z'
          summary_of_state_rights:
            - '2021-06-13T21:40:07.766Z'
          authorization_of_background_investigation:
            - '2021-06-13T21:40:08.766Z'
          signature:
            - '2021-06-13T21:40:09.766Z'
        metadata:
          ip_address: 73.9.149.180
          user_agent: Turn Mobile 1/1.4
      x-internal: true
    Timestamps:
      title: Timestamps
      required:
        - welcome
        - summary_of_rights
        - disclosure
        - summary_of_state_rights
        - authorization_of_background_investigation
        - signature
      type: object
      properties:
        welcome:
          type: array
          items:
            type: string
          description: ''
        summary_of_rights:
          type: array
          items:
            type: string
          description: ''
        disclosure:
          type: array
          items:
            type: string
          description: ''
        summary_of_state_rights:
          type: array
          items:
            type: string
          description: ''
        authorization_of_background_investigation:
          type: array
          items:
            type: string
          description: ''
        signature:
          type: array
          items:
            type: string
          description: ''
      example:
        welcome:
          - '2021-06-13T21:40:04.766Z'
        summary_of_rights:
          - '2021-06-13T21:40:05.766Z'
        disclosure:
          - '2021-06-13T21:40:06.766Z'
        summary_of_state_rights:
          - '2021-06-13T21:40:07.766Z'
        authorization_of_background_investigation:
          - '2021-06-13T21:40:08.766Z'
        signature:
          - '2021-06-13T21:40:09.766Z'
      x-internal: true
    Metadata:
      title: Metadata
      required:
        - ip_address
        - user_agent
      type: object
      properties:
        ip_address:
          type: string
        user_agent:
          type: string
      example:
        ip_address: 73.9.149.180
        user_agent: Turn Mobile 1/1.4
      x-internal: true
    ProfileRequest:
      title: ProfileRequest
      required:
        - first_name
        - last_name
        - email
        - phone_number
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        phone_number:
          type: string
      example:
        first_name: Tracy
        last_name: Noseworthy
        email: example@turning.io
        phone_number: '18645404931'
      x-internal: true
    200Success5:
      title: 200Success5
      required:
        - message
      type: object
      properties:
        message:
          type: string
      example:
        message: OK
      x-internal: true
    TaskRequest:
      title: TaskRequest
      required:
        - id
        - status
        - type
        - start_location
        - end_location
        - distance
        - start_date
        - end_date
        - duration
        - num_tasks
      type: object
      properties:
        id:
          type: string
        status:
          type: string
        type:
          type: string
        start_location:
          $ref: '#/components/schemas/StartLocation'
        end_location:
          $ref: '#/components/schemas/EndLocation'
        distance:
          type: number
        start_date:
          type: string
        end_date:
          type: string
        duration:
          type: number
        num_tasks:
          type: integer
          format: int32
      example:
        id: 1234-5678-9123
        status: completed
        type: delivery
        start_location:
          lat: '43.005895'
          lon: '-71.013202'
          formatted_address: '299 Main Street, Greenville, SC, USA'
        end_location:
          lat: '43.70895'
          lon: '-71.913202'
          formatted_address: '104 Greer Street, Greenville, SC, USA'
        distance: 3.5
        start_date: '2020-05-24 15:09:00'
        end_date: '2020-05-24 15:29:00'
        duration: 0.33
        num_tasks: 1
      x-internal: true
    StartLocation:
      title: StartLocation
      required:
        - lat
        - lon
        - formatted_address
      type: object
      properties:
        lat:
          type: string
        lon:
          type: string
        formatted_address:
          type: string
      example:
        lat: '43.005895'
        lon: '-71.013202'
        formatted_address: '299 Main Street, Greenville, SC, USA'
      x-internal: true
    EndLocation:
      title: EndLocation
      required:
        - lat
        - lon
        - formatted_address
      type: object
      properties:
        lat:
          type: string
        lon:
          type: string
        formatted_address:
          type: string
      example:
        lat: '43.70895'
        lon: '-71.913202'
        formatted_address: '104 Greer Street, Greenville, SC, USA'
      x-internal: true
    AddressRequest:
      title: AddressRequest
      required:
        - city
        - country
        - state
        - address_ln
        - postal_code
      type: object
      properties:
        city:
          type: string
        country:
          type: string
        state:
          type: string
        address_ln:
          type: string
        postal_code:
          type: string
      example:
        city: Spartanburg
        country: US
        state: SC
        address_ln: 299 Main Street
        postal_code: '29306'
      x-internal: true
    VehicleRequest:
      title: VehicleRequest
      required:
        - make
        - model
        - year
        - identification_number
        - identification_state
        - type
      type: object
      properties:
        make:
          type: string
        model:
          type: string
        year:
          type: string
        identification_number:
          type: string
        identification_state:
          type: string
        type:
          type: string
      example:
        make: honda
        model: accord
        year: '1999'
        identification_number: '239873243'
        identification_state: MO
        type: car
      x-internal: true
    PayoutRequest:
      title: PayoutRequest
      required:
        - id
        - status
        - type
        - payout_date
        - currency
        - gross_pay
        - deductions
        - net_pay
        - hours
      type: object
      properties:
        id:
          type: string
        status:
          type: string
        type:
          type: string
        payout_date:
          type: string
        currency:
          type: string
        gross_pay:
          type: number
        deductions:
          type: number
        net_pay:
          type: number
        hours:
          type: integer
          format: int32
      example:
        id: D123-2134-43234
        status: completed
        type: direct_deposit
        payout_date: '2020-06-11'
        currency: USD
        gross_pay: 20
        deductions: 5
        net_pay: 25
        hours: 1
      x-internal: true
    CareerRequest:
      title: CareerRequest
      required:
        - signup_date
        - length_at_work
        - total_hours_spent_working
        - first_activity_date
        - last_activity_date
      type: object
      properties:
        signup_date:
          type: string
        length_at_work:
          type: integer
          format: int32
        total_hours_spent_working:
          type: integer
          format: int32
        first_activity_date:
          type: string
        last_activity_date:
          type: string
      example:
        signup_date: '2020-01-04 19:00:00'
        length_at_work: 200
        total_hours_spent_working: 320
        first_activity_date: '2020-01-04 19:00:00'
        last_activity_date: '2020-06-20 11:21:17'
      x-internal: true
    ReputationRequest:
      title: ReputationRequest
      required:
        - rating
        - acceptance_rate
      type: object
      properties:
        rating:
          type: number
        acceptance_rate:
          type: number
      example:
        rating: 4.5
        acceptance_rate: 0.45
      x-internal: true
    ExternalProfileRequest:
      title: ExternalProfileRequest
      required:
        - first_name
        - last_name
        - email
        - phone_number
        - date_of_birth
        - address
        - task
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        phone_number:
          type: string
        date_of_birth:
          type: string
        address:
          $ref: '#/components/schemas/Address1'
        task:
          $ref: '#/components/schemas/Task'
      example:
        first_name: Alex
        last_name: Mendez
        email: your_email@turning.io
        phone_number: '18645404931'
        date_of_birth: '1987-05-24'
        address:
          city: Greer
          country: US
          state: SC
          address_ln: 299 Main Street
          postal_code: '29651'
          is_primary: 'True'
        task:
          id: 1234-5678-9123
          status: completed
          type: delivery
          start_location:
            lat: '43.005895'
            lon: '-71.013202'
            formatted_address: '299 Main Street, Greenville, SC, USA'
          end_location:
            lat: '43.70895'
            lon: '-71.913202'
            formatted_address: '104 Greer Street, Greenville, SC, USA'
          distance: 3.5
          start_date: '2020-05-24 15:09:00'
          end_date: '2020-05-24 15:29:00'
          duration: 1
          num_tasks: 1
      x-internal: true
    Address1:
      title: Address1
      required:
        - city
        - country
        - state
        - address_ln
        - postal_code
        - is_primary
      type: object
      properties:
        city:
          type: string
        country:
          type: string
        state:
          type: string
        address_ln:
          type: string
        postal_code:
          type: string
        is_primary:
          type: string
      example:
        city: Greer
        country: US
        state: SC
        address_ln: 299 Main Street
        postal_code: '29651'
        is_primary: 'True'
      x-internal: true
    Task:
      title: Task
      required:
        - id
        - status
        - type
        - start_location
        - end_location
        - distance
        - start_date
        - end_date
        - duration
        - num_tasks
      type: object
      properties:
        id:
          type: string
        status:
          type: string
        type:
          type: string
        start_location:
          $ref: '#/components/schemas/StartLocation'
        end_location:
          $ref: '#/components/schemas/EndLocation'
        distance:
          type: number
        start_date:
          type: string
        end_date:
          type: string
        duration:
          type: integer
          format: int32
        num_tasks:
          type: integer
          format: int32
      example:
        id: 1234-5678-9123
        status: completed
        type: delivery
        start_location:
          lat: '43.005895'
          lon: '-71.013202'
          formatted_address: '299 Main Street, Greenville, SC, USA'
        end_location:
          lat: '43.70895'
          lon: '-71.913202'
          formatted_address: '104 Greer Street, Greenville, SC, USA'
        distance: 3.5
        start_date: '2020-05-24 15:09:00'
        end_date: '2020-05-24 15:29:00'
        duration: 1
        num_tasks: 1
      x-internal: true
    200SuccessBasicInfo:
      title: 200SuccessBasicInfo
      required:
        - message
      type: object
      properties:
        message:
          type: string
      example:
        message: OK
      x-internal: true
    /onboardingsrequest:
      title: /onboardingsrequest
      required:
        - name
        - steps
      type: object
      properties:
        name:
          type: string
        steps:
          type: array
          items:
            $ref: '#/components/schemas/Step'
          description: ''
      example:
        name: Onboarding Flow
        steps:
          - name: Handoff
            order: 0
          - name: Phone Interview
            order: 1
          - name: Background Check
            order: 2
      x-internal: true
    Step:
      title: Step
      required:
        - name
        - order
      type: object
      properties:
        name:
          type: string
        order:
          type: integer
          format: int32
      example:
        name: Handoff
        order: 0
      x-internal: true
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
  - httpBearer: []
tags:
  - name: Workforce
    description: |-
      Turn centralizes data on each worker to define a unique job profile consisting of identity and performance data.
      Partners provide this information to Turn through the Workforce API.

      ## About *turn_id*
      The turn_id is the unique id provided by Turn through the screening of a candidate. This unique id is an 11 character string starting with a ‘C’ and followed by 10 digits (ex. C1279030625).
      The Turn ID is required to be specified in the URL indicated as <turn_id> in the documentation. 
      If the Turn ID is not included, the information will not be correctly shared.

      ## About record *id*
      Some records posted have a unique id. These unique ids are the identifiers generated by your system and do not need to follow a specified format. They can be sequential numbers or an alphanumeric UUID system.
